package(default_testonly = 1)

subinclude("//testing/build_defs:junit4_test_suites")

java_test(
    name = "CallBuilderTest",
    srcs = ["CallBuilderTest.java"],
    deps = [
        "//java/com/google/callbuilder",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)

java_test(
    name = "UnificationTest",
    srcs = ["UnificationTest.java"],
    deps = [
        "//java/com/google/callbuilder",
        "//third_party:guava",
        "//third_party:junit4",
        "//third_party:truth",
    ],
)